### ISSUE TITLE
Sci & Med need shit roundstart

### ISSUE THREAD

**Issue by Lyroth001** [Pixeltheaertist/Trieste-Port-14#113]
## Description
Sci needs
[ ] APEs
[ ] Anom containment
[ ] Anom generator

Med needs
[ ] resources

**Comment by Pixeltheaertist** [comment]
honestly med needs chemistry. Horrible idea on my part to put it 11KM away from med. I'm going to replace the chemistry room with the marine biology lab someday

**Comment by Pixeltheaertist** [comment]
my one worry about the anom generator is it might spawn out somewhere randomly in the ocean

**Comment by Pixeltheaertist** [comment]
the map is HUGE, so it would be pretty much impossible to find it

**Comment by Pixeltheaertist** [comment]
> Fair, they at least need APES to handle randomly spawned anoms/infections when they are merged

yess... that electric anom was an issue
Maybe a new kind of anomaly generator that makes the anomaly right there? But anomalies would be harder to contain to combat it or something

**Comment by Pixeltheaertist** [comment]
med now has like 4 topical lockers spread around, as well as a stasis bed and a morgue far south
