### ISSUE TITLE
Make the diving bell indestructable

### ISSUE THREAD

**Issue by Lyroth001** [Pixeltheaertist/Trieste-Port-14#114]
## Description
title - major issues if its broken

**Comment by Pixeltheaertist** [comment]
diving bell is now a ProtectedGrid, shouldn't be able to be damaged. Docking ports can still be damaged, but engineering did an awesome job fixing it last time

seriously, throwing a foam grenade and then drilling an airtight tunnel to the docking port is fucking GENIUS, i was literally so happy
