### ISSUE TITLE
Perma is trivial to break out of

### ISSUE THREAD

**Issue by Lyroth001** [Pixeltheaertist/Trieste-Port-14#126]
## Description
Literally took me like a minute with the tools inside, perma either needs to be heavily reinforced, and/or the scaffold outside it needs to be removed. We don't have the threat of spacing to discourage breaking the window, so the grill should be electrified and there should be something stopping just walking out

Alternatively could be moved to Sweetwater (but that would require moving sec. Probably not ideal)

**Comment by Pixeltheaertist** [comment]
> ## Description
> Literally took me like a minute with the tools inside, perma either needs to be heavily reinforced, and/or the scaffold outside it needs to be removed. We don't have the threat of spacing to discourage breaking the window, so the grill should be electrified and there should be something stopping just walking out
> 
> Alternatively could be moved to Sweetwater (but that would require moving sec. Probably not ideal)

i fully aggree. The current one is there because chasms used to instakill you and RR you, but now that you actually fall somewhere i think jumping out of the window in perma to escape is much more interesting

**Comment by Pixeltheaertist** [comment]
perma no longer has catwalks outside the window, and the grilles are shocked
