### ISSUE TITLE
Borgs should take damage in water

### ISSUE THREAD

**Issue by Pixeltheaertist** [Pixeltheaertist/Trieste-Port-14#63]
Borgs will take damage if in water, eventually shutting down.

We honestly need a system that interacts with water anyways, since i want water specific guns and such in the future. A system that checks the gas around an object.

**Comment by Lyroth001** [comment]
Ok im gonna start looking into this, no promises about speed :)

**Comment by Pixeltheaertist** [comment]
all good! any help is better than no help :)

**Comment by Lyroth001** [comment]
Ok i vaguely know what im doing now so hopefully this shouldnt take too long :godo:

**Comment by Pixeltheaertist** [comment]
> Ok i vaguely know what im doing now so hopefully this shouldnt take too long :godo:

copy that! Take all the time ya need, i'm still doodling around with Jellids n' stuff
(i'm scared to try and do the ocean midmap)

**Comment by Lyroth001** [comment]
Tbf I havent tested anything yet so it may all fall apart, but i'm hopeful lmao

**Comment by Lyroth001** [comment]
Also turns out barotrauma was the correct system to steal from
