### ISSUE TITLE
InWater System needs some kind of damage icon on it

### ISSUE THREAD

**Issue by Lyroth001** [Pixeltheaertist/Trieste-Port-14#75]
## Description

Currently you take damage without any indicator beyond inspecting yourself. Requires an icon (see barotrauma system).

Opening this to show it is known, i'll just use that H2O icon for now. May also refactor InWater a bit >:)

**Comment by Pixeltheaertist** [comment]
cool cool, check out the gunbolt branch, i made some tweaks from my laptop, i'm not sure if it works or not but it should make InWaterSystem declare isInWater as true when in water, allowing other systems to reference it, like for example gunbolt hopefully making it so guns can't fire underwater

**Comment by Pixeltheaertist** [comment]
![image](https://github.com/user-attachments/assets/7e141221-48bf-4de0-8557-2ba6e4aed62b)
![image](https://github.com/user-attachments/assets/d6a9ead4-afd1-4066-be54-c5216c0671f4)
![image](https://github.com/user-attachments/assets/040d01ab-d41d-42aa-985e-3a7860a800d2)


it might be a little needlessly complex, i can't test it from this laptop but lmk if it works, if it doesn't i'll just delete the branch, just an experiment @Lyroth001

**Comment by Lyroth001** [comment]
If we put a dependency on inwater system, we can just call the method directly i think

**Comment by Pixeltheaertist** [comment]
interesting

**Comment by Pixeltheaertist** [comment]
You know, i bet somewhere in the future we could make it so when you enter the ocean it applies like a softer version of the cateract shader, making the peripherals a bit blurry since you're underwater or smth
