### ISSUE TITLE
Trieste Waste-Zone

### ISSUE THREAD

**Issue by Pixeltheaertist** [Pixeltheaertist/Trieste-Port-14#79]
The ocean surface under Trieste is where people fall, where an elevator/tram will take you, and it's where i think it could be interesting to have the surface version of Maints.

Small interconnected trash islands, crappy buildings, maints loot. It's where antagonists will go to plan and gear up, where tiders can go to make tiderland or make a drug lab. Everything thrown off the platform will end up here, where it amalgamates into a much smaller town-type thing at the surface.

thoughts?

we're going to need "trash tile" sprites, which are tiles of amalgamated rusty garbage with a displacement map or wtv it's called (the thing grass uses to spill onto neighboring tiles), so it looks scrappy and like trash.

Here we could also have like ghost role "waste-processing" borgs or something, old unmaintained quadrupeds that eat trash or process it like a recycler. And other just miscellaneous old tech and crap that can be used for little niche experiments or building.

**Comment by RoR2enjoyer** [comment]
I found you
It is I 
Piss wizard
