### ISSUE TITLE
Discord feature req buttons still link to upstream discord

### ISSUE THREAD

**Issue by Lyroth001** [Pixeltheaertist/Trieste-Port-14#89]
Config stuff i assume but this seems. Not ideal.

**Comment by Pixeltheaertist** [comment]
wait where?

**Comment by Lyroth001** [comment]
![image](https://github.com/user-attachments/assets/56bf38cc-927c-40e0-bd23-0dc6d3a539b0)
The buttons here, after you press the new issue button, press feature request, goes to upstream

**Comment by Pixeltheaertist** [comment]
oh neat

**Comment by Pixeltheaertist** [comment]
removed it since i don't have the discord link and anyone here prolly came from the discord

**Comment by Pixeltheaertist** [comment]
wahoo
